### ISSUE TITLE
Useful for saved search?

### ISSUE THREAD

**Issue by askeeve** [facelessuser/RegReplace#2]
Would this package be useful for saving some hard-coded searches to aid in navigating a source?  For example, to jump between the first line of code in a function?

```
:Code FUNC
//comment
//comment
//comment
x=y;
```

In the above example, I'd like to be able to jump to the x=y line.  Also, Does RegReplace allow for directional searching?

**Comment by Enteleform** [comment]
Kind of related, but I think a bit different also.

Is it possible to search and highlight all results from commands?
( __+1__ for the directional searching you guys mentioned also )

I have the following settings:

### @ Default.sublime-commands
```
     {
         "caption": "RX: Find Double Newlines",
         "command": "reg_replace",
         "args": {"replacements": ["double_newlines"]}
     },
```

### @ reg_replace.sublime-settings
```
    "replacements": {
        "double_newlines": {
            "find": "\n\n\n"
        },
    },
```

Currenty, if I run `RX: Find Double Newlines` from the command palette, all instances of the RegEx pattern will be replaced with a `NUL` character.

My intended use is for the command to highlight all instances of the pattern, rather than replace them.

**Comment by facelessuser** [comment]
This issue has been open for years, and it just hasn't bubbled up as a high enough priority. Close as this issue is quite stale. 

@gir-bot add wontfix
