### ISSUE TITLE
RegReplace commands not appearing in command palette

### ISSUE THREAD

**Issue by mattkurtis** [facelessuser/RegReplace#25]
I am using Sublime Text 2 64 bit on Windows 7. I installed RegReplace by downloading from GitHub and placing in my Packages folder. I then restarted Sublime Text, but none of the commands showed in the command palette. I then uninstalled Sublime Text, cleared out my user folder under AppData, and downloaded and installed the latest Sublime Text 2 (2.0.2).

I redownloaded the GitHub file, extracted and renamed the folder to RegReplace. I deleted the .gitignore and readme.md files and then pasted the folder in my Packages directory. Then I opened Sublime Text and now I can access the menu options from the command palette (the 4 Preferences options), but none of the commands show up. I expected that the Clear Highlights command would be available. I uncommented all the example commands and restarted Sublime, but they still don't appear in the command palette.

Have you seen this behavior before? Did I miss a step on the install?

**Comment by facelessuser** [comment]
I would install from [Package Control](https://packagecontrol.io/installation).  Manual installation is not recommended (mainly because people often do it incorrectly).  Package Control guarantees a more reliable install: installs correct branch, installs to correct location, updates when new versions are available etc.
