### ISSUE TITLE
Commands not showing up ST3 OS X 10.9.5

### ISSUE THREAD

**Issue by flopflip21** [facelessuser/RegReplace#31]
I installed via package control, no errors on the console about RegReplace.

I have these files.
~/Library/Application Support/Sublime Text 3/Packages/User/reg_replace.sublime-settings
~/Library/Application Support/Sublime Text 3/Packages/User/Default.sublime-commands

There's no folder in Packages called RegReplace though?

Also the files are doubling up like this
![a](https://cloud.githubusercontent.com/assets/11042561/7469014/28ba49f4-f30f-11e4-9790-c12f56fc7afe.png)

**Comment by facelessuser** [comment]
> There's no folder in Packages called RegReplace though?

Because Package Control by default installs zipped version in `~/Library/Application Support/Sublime Text 3/Installed Packages/`.

> Also the files are doubling up like this

I only have them defined once https://github.com/facelessuser/RegReplace/blob/master/Default.sublime-commands.

If you are seeing double, maybe you have saved a duplicate file in your User folder with these commands defined, or maybe Package Control did something.  But I can confirm there is nothing wrong with RegReplace on my end.

So from my end everything is fine.

**Comment by facelessuser** [comment]
I haven't heard anything else to contradict my early statement, so I will consider this issue closed.

**Comment by difelice** [comment]
I'm having the same problem, @flopflip21 how did you solve this?
