### ISSUE TITLE
Add support for replacement rule patterns

### ISSUE THREAD

**Issue by JoBrad** [facelessuser/RegReplace#33]
Is it possible to run all commands in the replacements array? I tried some variations in the commands file, but wasn't able to get it working. 
```json
{
	"caption": "Reg Replace: Insert Pentaho Variables",
	"command": "reg_replace",
	"args": {"replacements": []},
	"regex_full_file_with_selections": true
}```

**Comment by facelessuser** [comment]
Yes, you can run all replacements if you add all replacements to your array.

When I designed this, I was unable to conceive a scenario where I would want to **always** load all replacements.  I work in multiple languages, so not all replacements would **always** apply for me.  Even if I did work in one language, some changes are specific to a project.  It may be worth creating for the project, but long term it won't be relevant.  Also, for instance, in personal projects, I always strip trailing spaces from all lines; at work I **cannot** strip all trailing whitespace unless I am writing a new file from scratch as it will create large diffs in existing files and make it that much more difficult to merge my small changes if I am affecting the entire file causing merge conflicts.  Some replacements I need to be able to call on demand in certain scenarios.

**Comment by JoBrad** [comment]
I understand that I can enumerate each item, but is there a way to use some wildcard or other form of notation, so that all items in the replacements array are applied, without them being specifically enumerated?

**Comment by JoBrad** [comment]
By the way - really love this plugin! It took me some time to configure, but it was certainly worth the effort!

**Comment by facelessuser** [comment]
> I understand that I can enumerate each item, but is there a way to use some wildcard or other form of notation, so that all items in the replacements array are applied, without them being specifically enumerated?

Nope, not at this time.  I guess I am open to it, but I have no immediate plans to implement something like that.

> By the way - really love this plugin! It took me some time to configure, but it was certainly worth the effort!

Thanks.  Yeah, I know it takes a bit to get familiar with it and get it set up, but it sure saves time afterwards :).

**Comment by facelessuser** [comment]
Thinking about this more.  I am concerned as a wildcard pattern include has no order.  I am not sure the specific intention of use here, but I personally know that a number of my pattern sequences require certain patterns to be run before others.  It just seems like this feature would be even more limited.  It would only be useful if you intend to run a number of patterns that are all completely stand alone and the order of which would not affect the final outcome.

**Comment by JoBrad** [comment]
Ideally, running all entries would run them in order, as they are listed). However, for my specific query, the order didn't matter. I am replacing pieces of text in SQL/Java scripts with parameters, or reversing that process to replace parameters with values, so I can quickly test a script in QA, or update a tested script so it will use parameters to reference environment-specific values. As I develop new scripts, the goal was to be able to add to this replacement list, and have the new replacements be picked up without having to configure it in another place, as well.

**Comment by facelessuser** [comment]
> Ideally, running all entries would run them in order, as they are listed).

That's a problem as we are using an **unordered** collection of name/value pairs.  JSON doesn't order their objects.  I suppose if we had used an array, it would be ordered, but I liked the quicker lookup of a hash table instead of having to manually walk the array looking at each index's name to find what we are looking for.  So currently, you aren't going to get it ordered, and I don't plan on reworking the format of the settings file at this time.

With that said, I don't see why you couldn't write a wrapper command for your personal use that parses the rules in `reg_replace.sublime-settings` using some wild card pattern and feed those to the `reg_replace` command.  If I **was** going to add this directly, this is probably all I would do.  But it can easily be done outside of RegReplace as a personal plugin.

```python
import sublime
import sublime_plugin

class WildcardReplaceCommand(sublime_plugin.TextCommand):
    def run(self, edit, wildcard):
        rrsettings = sublime.load_settings('reg_replace.sublime-settings')
        mypatterns = []
        # Some code to parse the settings file with wildcard and populates mypatterns
        self.view.run_command('reg_replace', {'replacements': mypatterns})
```

It just seems like you have a very specific use case, and I am having a hard time justifying such a feature that I don't think applies more generally.  If it was something that applied more generally, then I probably wouldn't have a problem with it.  I guess if enough people requested it, I might be swayed, but currently, I am thinking this might be better suited as a personal plugin to wrap the `reg_replace` command.

**Comment by JoBrad** [comment]
Fair enough. Thanks for the additional info, and your time.
