### ISSUE TITLE
Off by one problem in replace with extended back reference

### ISSUE THREAD

**Issue by grosenberg** [facelessuser/RegReplace#39]
The replacement rule is intended to swap the order of the parameter (type variable) tuple -- converting from Java to Go syntax.  With the extended back reference parameter on, there is an extra trailing paren that is injected.  Turning the back reference parameter off or putting a space between the \\4 and \\5 parameters will make the extra paren go away. Rather sneaky little bug.

Appreciate if you could take a look when you have a chance.

[problem.go.txt](https://github.com/facelessuser/RegReplace/files/33643/problem.go.txt)
[reg_replace.sublime-settings.txt](https://github.com/facelessuser/RegReplace/files/33642/reg_replace.sublime-settings.txt)

**Comment by facelessuser** [comment]
Thanks.  That is definitely a problem.  I will take a look at it.

**Comment by facelessuser** [comment]
Okay, I think I found the problem.  I wasn't handling group boundaries correctly when I got a group with zero width.  So then we would grab a character when we should have returned nothing.  The fix is over at https://github.com/facelessuser/Rummage/issues/92.  I will merge it in here tomorrow and get a bug fix release out.

**Comment by facelessuser** [comment]
Release 2.10.1 has been made.  Thanks again for reporting your issue.  Catching those corner cases I forgot to unittests can sometimes exist for a bit if no one reports them.  Thanks!
