### ISSUE TITLE
Using character class 'print' as 'find' value isn't working as expected

### ISSUE THREAD

**Issue by Patuti** [facelessuser/RegReplace#42]
I tried to create a replacement like this:
```json
    "replacements": {
        "remove_non_printable_chars": {
            "find": "[^[:print:]]",
            "replace": "",
            }
        }
```

And then applying it with a command like this:
```json
    {
		"caption": "Reg Replace: Remove Non-Printable Chars",
		"command": "reg_replace",
		"args": { "replacements": ["remove_non_printable_chars"] }
	}
```

Is not matching the same thing as when using the same pattern with sublime's built-in search.
For example I had a file filled with NAK (0x15) and looked them with the built-in search using regex + [^[:print:]] and it found all of them. But when using the reg replace command above, it didn't find them.

I've attached a sample file with the 0x15 chars.
[regreplace_issue_sample.txt](https://github.com/facelessuser/RegReplace/files/106015/regreplace_issue_sample.txt)

**Comment by facelessuser** [comment]
I didn't actually set out to write such a long answer.  For the short version, skip to the last paragraph.  Basically what you want should work if you update the `backrefs` dependency.  For a detailed answer on why RegReplace may differ from the Sublime find panel results read from the beginning.

1. `[:print:]` will not work unless you enable `extended_back_references` in the settings file.

2. RegReplace does not use the same regex engine that the Sublime find panel does.  It uses Python's re module.  So do not expect a 1:1 feature match.

2.  `[:print:]` functionality does not exist in the re module, but I wrote a module that wraps around Python's re that adds new character classes and additional back references.  It is called backrefs and in the RegReplace documentation I link to the backrefs [manual](http://facelessuser.github.io/RegReplace/usage/#extended-back-references).  You can read all about what backrefs does and does not do there.  But as it looks like that manual is a little out of date, I will summarize here.

`[:print:]` is the POSIX character class which is ASCII based.  Different regex engines treat this different (possibly not as true POSIX) or do not treat it at all.  I treat it as POSIX which is ASCII.  The table showing their translation is available here: https://github.com/facelessuser/sublime-backrefs/blob/master/readme.md#posix-style-properties-1 (the Unicode column isn't really accurate anymore as things internally changed and I forgot to update the table to reflect those changes: see next paragraph).

In the current implementation POSIX is always POSIX now.  When using the Unicode property variant `\p{print}` instead of `[:print:]`, if the property name already maps to a Unicode property name, the Unicode property will be used instead of the POSIX form.  To force the POSIX form when using the Unicode property notation you must prefix `posix` to the name.  If the name does not already map to a Unicode property name, the name will be an alias for `\p{posixname}`.  In this case `print` is not a Unicode property name, so `\p{print}` will translate to `\p{posixprint}` which is the same as `[:print:]`.

Keep in mind the Unicode tables for Unicode properties are generated from the Unicode version used by the Python install that is being used.  Sublime uses Python 3.3 which internally used Unicode 5.3 I think.  This is done to keep all the Unicode references consistent with the re module's internal Unicode translation.

Now that I got all of that out of the way...

I tired out your example and it works fine for me.  Make sure `extended_back_references` is enabled in your settings file and try running the `Satisfy Dependency` command from the command palette which should update all of your dependency modules to the latest (including `backrefs`) and restart Sublime.  I imagine it should work for you then.  Do not expect a 1:1 match with how Sublime treats regex in its find panel and how RegReplace treats it.

**Comment by Patuti** [comment]
Thanks for the explanation!
I guess I missed the information that the regex engine is not the same, I really assumed it was the same, that's why I made the comparison and didn't try to investigate further.

I'll try your suggestion as soon as I have some spare time and will close or update the issue, thanks again!

**Comment by facelessuser** [comment]
No problem.  I think Sublime uses boost in the find panel or maybe oniguruma.  I get confused because the find panel regex is not the same as the syntax file engine...or maybe the snippet file...I can't recall the details exactly.  I think recently Jon even tweaked whatever engine he's using in the syntax files.

Anyways, the Sublime API does have some access to one of those engines, but I found the flexibility of using the API a little too restrictive for what I wanted to do, so instead I used Python's re so I could manipulate things at a lower level.

**Comment by Patuti** [comment]
Sorry for the long delay. As you said, it works as expected with ``` extended_back_references ```.

I may have found something interesting during my real world test with it. I tried to use it on a bigger file than the sample one (>4mB), mostly "regular" text and some matches of ``` [^[:print:]] ```, and the plugin process "freezed" for some time, I ended killing it as I wasn't seeing any considerable CPU usage.

As soon as I have the time I'll let it run longer so that I'm sure this is no infinite loop somewhere.
What I observed with Process Explorer was that the plugin_host process was using ~12% CPU while increasing mem usage and after some time it falls back to less than 1% usage and seems to remain like that, but I'll let you know if I find something interesting.

Thanks again for your help!
