### ISSUE TITLE
[Question] Don't work markdown link replace

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/RegReplace#55]
### 1. Summary

I don't understand, why one of my rules don't work as expected. `****<http://kristinita.ru>****` don't convert to `**<http://kristinita.ru>**`.

### 2. Settings

My `User\reg_replace_rules.sublime-settings` file:

```json
{
    "replacements":
    {
        // Change <link> to **<link>**
        "sasha_urls":
        {
            "find": "(**<http.*?>**)",
            "replace": "**\\1**",
        },
        // Remove unexpected asterisks
        "sasha_remove_4_asterisks_begin":
        {
            "find": "\\*\\*(\\*\\*<)",
            "replace": "\\1",
        },
        "sasha_remove_4_asterisks_end":
        {
            "find": "(>\\*\\*)\\*\\*",
            "replace": "\\1",
        },
    }
}
```

My `User\Default.suricate-profile` file (I use [**Suricate**](https://packagecontrol.io/packages/Suricate) framework for commands):

```json
{
    "user_commands": {
        // Link decoration
        "sasha_markdown_decoration": {
            "caption": "Markdown Decoration",
            "call": "sublime.reg_replace",
            "args": {
                "replacements": ["sasha_urls", "sasha_remove_4_asterisks_begin", "sasha_remove_4_asterisks_end"]
            }
        }
    }
}
```

My `test.md` file:

```markdown
<http://kristinita.ru>

**<http://kristinita.ru>**

****<http://kristinita.ru>****

**<example>**
```

### 3. Expected behavior

```markdown
**<http://kristinita.ru>**

**<http://kristinita.ru>**

**<http://kristinita.ru>**

**<example>**
```

### 4. Actual behavior

Third line don't convert as expected.

```markdown
**<http://kristinita.ru>**

**<http://kristinita.ru>**

****<http://kristinita.ru>****

**<example>**
```

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

<kbd>Ctrl+Shift+P</kbd> → `Suricate: Markdown Decoration` → I get actual behavior.

### 6. Environment

- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 3.2.0
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- regex ver.: 2.4.112
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

Thanks.

**Comment by facelessuser** [comment]
@Kristinita 

1. This is not an issue RegReplace, but with your usage of regular expression.

2. Your very first pattern `(**<http.*?>**)` is not valid regular expression, the fact that Python's re even recongnizes this is surprising to me.  I imagine what you were going for was `(\**<http.*?>\**)` or mabye `(\*\*<http.*?>\*\*)`, but I have no idea what your actual intentions were.

3.  Whatever you were hoping to accomplish with pattern 1, I imagine it will not give you the expected output for other reasons as well.  Let's take a look. `(**<http.*?>**)` --> `(group 1)`.  So using this find `(\**<http.*?>\**)` and this replace `**\1**` on this text `****<http://kristinita.ru>****`, we will get `******<http://kristinita.ru>******`.

    I'm going guess what you want.  I assume you want to use `\**(<http.*?>)\**` and `**\1**`. `****<http://kristinita.ru>****`, we will get `**<http://kristinita.ru>**`.

Remember that the actual finding and replacing is done by either Python's Re or the 3rd party Regex  module.  All RegReplace does is string together a bunch of find and replaces (I'm over simplifying, but what I'm trying to say is that I am not using my own search engine). Yes there *could* be bugs in the regular expression engines being used, but they are dependencies of RegReplace, not modules I directly maintain.  99 times out of 100, when people are getting unexpected results from their regular expression patterns in RegReplace, it is because their patterns are faulty.

Here is my general advice.  If you aren't 100% confident in your regular expression ability, you should probably test out your patterns individually to understand how they actually behave before stringing them all together in a sequence.  It will make things easier to debug as you won't be overwhelmed by the compound results of 3 different patterns' results.

**Comment by Kristinita** [comment]
@facelessuser , oops, I'm sorry, my first pattern is

```json
		"sasha_urls":
		{
			"find": "(<http.*?>)",
			"replace": "**\\1**",
		},
```

**Comment by Kristinita** [comment]
@facelessuser ,

> Here is my general advice. If you aren't 100% confident in your regular expression ability, you should probably test out your patterns individually to understand how they actually behave before stringing them all together in a sequence. It will make things easier to debug as you won't be overwhelmed by the compound results of 3 different patterns' results.

Yes, I I did this. If I use only second and third templates, I get expected behavior:

`****<http://kristinita.ru>****` → `**<http://kristinita.ru>**`

But with first template, I no get expected behavior.

I'm sorry, my typo take a lot of your time 😢 .

**Comment by facelessuser** [comment]
> I'm sorry, my typo take a lot of your time :cry: .

No worries :slightly_smiling_face:.
