### ISSUE TITLE
Override scope from the sublime-commands file

### ISSUE THREAD

**Issue by Asuza** [facelessuser/RegReplace#57]
## Feature Request

Thank you for creating this incredibly useful plugin!

I would love to be able to specify the scope for several replacements at once, by defining it in the sublime-commands file.

Currently, I need to write rules like this:
```json
{
    "replacements": {
        "expand_bedroom": {
            "find": "Bdrm",
            "replace": "Bedroom",
            "scope": "source.tt.tag"
        },
        "expand_bathroom": {
            "find": "Btrm",
            "replace": "Bathroom",
            "scope": "source.tt.tag"
        }
    }
}
```
Ideally I would be able to remove all "scope" properties from my replacements and define it in the sublime-command file:
```json
[
    {
        "caption": "Reg Replace: PVAL BA to PSI alpha",
        "command": "reg_replace",
        "args": {
            "scope": "source.tt.tag",
            "replacements": [
                "expand_bedroom",
                "expand_bathroom"
            ]
        }
    }
]
```

It's not a big deal if you only have a couple of replacements, but I've got over 300 now (all the same scope). Plus, this change would allow you to use the same replacement in different scopes depending on the command you set up.

## Support Info
- ST ver.: 3131
- Platform: linux
- Arch: x64
- Plugin ver.: 3.2.1
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- regex ver.: 2.4.112
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
The reg_replace command is a command that chains searches.  Each entry is an independent search rule. I kind of want to keep it that way.  I can understand why you'd want it as you have a very unique use case, but I am doubtful of how common these scenarios are.  And I really don't want to open the door to the chain command overriding all sorts of things.

I feel you might be better off with something like a single search rule that has a search pattern of `(Bdrm|Btrm)` and instead of getting fed a replace pattern, you give it a [custom replace plugins](http://facelessuser.github.io/RegReplace/usage/#custom-replace-plugins) that looks at the match returned and gets the replacement out of a dictionary.  Have you looked at the custom replace plugins? I think that may be more what you need.

I think this is more of an approach problem than it is a problem that requires the plugin to change.

**Comment by Asuza** [comment]
That does seem like it would be a better solution for what I'm doing. I saw the feature earlier today, but only skimmed it because I don't know Python that well.

I was able to get what I wanted done using only `replacement` configurations, but I'm going to try the plugin style to keep it more maintainable. As it is now, my _reg_replace_rules.sublime-settings_ is over 1500 lines.

Essentially, I'm trying to find items in a very long list and replace them with corresponding items in a separate list, sort of a giant refactor. If you have a separate feature I may have missed to accomplish that, I'd love to know more (still going to start the plugin in the meantime, however).

**Comment by facelessuser** [comment]
I think the plugin is the best approach and it should be pretty easy.

Replace pattern:

```
(Bdrm|btrm)
```

Then a plugin something like this:

```py
replacements = {
   "Bdrm": "Bedroom",
   "Btrm": "Bathroom"
}

def replace(m):
    # Get first capture group
    key = m.group(1)
    # Try and find key in dict, if key not found, just return key
    return replacements.get(key, key)
```

**Comment by facelessuser** [comment]
Let me know if you have more questions.

**Comment by Asuza** [comment]
Just in case someone happens across this issue and needs to use replacements with regex involved, this is what I came up with:

```python
replacements = {
    "(The)?Abbr": "Abbreviation",
    "(One)?Fruit": "Banana"
}

import re

def replace(m):
    keys = replacements.keys()

    for key in keys:
        matches = re.match(key, m.group(0))

        if matches:
            return replacements.get(key)

    return m.group(0);
```

**Comment by facelessuser** [comment]
Glad you got it working.  I love regex, but sometimes regex alone isn't enough.  Hopefully this opens up some new possibilities for you with RegReplace.
