### ISSUE TITLE
find_only behavior changes when a scope is specified

### ISSUE THREAD

**Issue by Asuza** [facelessuser/RegReplace#58]
## Bug?

When `find_only` is used without a scope, only the matches are outlined. If `find_only` is used *with* a scope, then the scope is outlined, rather than the match.

*no scope*:
![no scope](http://i.imgur.com/HaesHke.png)
*scope*:
![scope](http://i.imgur.com/ul8plGZ.png)

## Support Info
- ST ver.: 3131
- Platform: linux
- Arch: x64
- Plugin ver.: 3.2.1
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- regex ver.: 2.4.112
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Define a command with `find_only: true`
2. Define a replacement with no `scope` set
3. Run the rule on an appropriate file. Only the matches should be outlined.
4. Update the replacement to include an appropriate `scope`.
5. Run the rule again on the same file. Now, the scope should be outlined rather than the match.

**example file to search, set as HTML syntax**
```html
<script>
    let theGoodTimes = "roll";
</script>
```
**example command**
```json
    {
        "caption": "Reg Replace: Test Scope Bug",
        "command": "reg_replace",
        "args": {
            "find_only": true,
            "replacements": [
                "scope_bug"
            ]
        }
    }
```
**example rule**
```json
        "scope_bug": {
            "find": "\\btheGoodTimes\\b",
            "replace": "boulders",
            "scope": "source.js.embedded.html"
        }
```

**Comment by facelessuser** [comment]
This is well understood with scope searches and isn't technically a bug.  When doing find only, it stops after it finds the scopes.  It's just due to how it is implemented.  I've had on my list for a while merging scope logic and non-scope logical, and treating scope find more like selection regions. Essentially this would unify how these two work and send them down the same pipe allowing scope highlights to work more as one would expect.  Alas, the time has eludes me still.

**Comment by facelessuser** [comment]
I think I have a way to make this more intuitive moving forward.

**Comment by facelessuser** [comment]
Current branch under testing is found here: https://github.com/facelessuser/RegReplace/tree/better-scope-actions
