### ISSUE TITLE
My code doesn't work.

### ISSUE THREAD

**Issue by thehung2224** [facelessuser/RegReplace#63]
Here is my configuration, I don't know why it doesn't work. Hope you can help me out

```
name = "test"

find = r"\[center\](http://.*?fastpic.+?)\s\[b\](\w+(?: \w+)*) - (\w+(?: \w+)*) \(\d+\) \(\w+\)\[/b\]\s*Released: (.+?) \| Track: (.+?) \| Country: (.+?) \| (.+?) \| Time: (.+?) \| Label: (.+?)-\s?(.+?)(|\n|\s?\|) \| (.+?) \| (.+?) \| (\w+(?: \w+)*)\s*\[i\]Genre: (.+?)\[/i\]\s*\[/center\]\s*\[cut\]\s*(\[b\](.+?)\[/b\])\s+\[quote\]([\s\S]+?)\[/quote\]\s*\[quote\]\[center\]\s*\[b\]NitroFlare\[/b]([^=])(http://nitroflare\.com[^\s]+)\s*\[b\]Uploaded\[/b]([^=])(https://uploadgig\.com[^\s]+)\s*\[/quote\]\[/center\]"

replace = r"[center][img]$1[/img][/center][b]Artist:[/b] $2\n[b]Country:[/b] $6\n[b]Album:[/b] $3\n[b]Genre:[/b] $15\n[b]Label (Catalog#):[/b] $9[$10]$11\n[b]Year Of Release:[/b] $4\n[b]Format:[/b] $7 (* tracks)\n[b]Size:[/b] $14\n\n$16\n$18$19[url=$20]Nitroflare[/url]\n$21[url=$22]Uploadgig[/url]"
```

**Comment by facelessuser** [comment]
Are you  having an issue with the plugin, or are you hoping I am going to debug your massive regular expression?

Do more simplistic cases work for you? Or is this your first time using RegReplace?

I have no idea what your issue is as you haven't taken the time to explain it.  Keep in mind I am more than happy to help with general setup, and debugging plugin issues, but I don't really have time to come up with solutions for people's work.

If you are uncertain if the plugin is working, try a simple example first.  Keep in mind, you need more than a find and replace rule, but you need to formulate a command with that uses that rule as well (see documentation for more info).

Please update your issue with a detailed explanation of what your issue is, and please let me know if you've successfully gotten simple examples to work.

**Comment by facelessuser** [comment]
Unfortunately, I've heard no response on over a month. I cannot help you if you do not respond to my questions. I will close this issue as it has gone stale.
