### ISSUE TITLE
Chaining back references

### ISSUE THREAD

**Issue by displayadrian** [facelessuser/RegReplace#86]
## Description

I'm having trouble getting the plugin to find two special characters in a row:

```
{
	"replacements":
	{
		"WestCoast_2pm_placement":
		{
			"name": "WestCoast_2pm_placement",
			"find": "_1-_-{\\u003F\\u0024contacts_data_17\\u003F}-_-}",
			"replace": "_1-_-WestCoastB-_-"
		}
	}
}
```

The `\\u003F\\u0024` sequence isn't working. I've scoured the backrefs documentation but I'm not getting anywhere. Is there another way to chain special characters like this?

## Support Info

- ST ver.: 3176
- Platform: osx
- Arch: x64
- Plugin ver.: 3.8.0
- Install via PC: True
- mdpopups ver.: 3.4.0
- backrefs ver.: 3.5
- regex ver.: 2.4.130
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Paste the above code into reg_replace_rules.sublime-setttings
2. Assign it to a command via 'Preferences > Package Settings > RegReplace > Commands - User' using this code:

```
[ 
    {
         "caption": "Reg Replace: West Coast 2pm",
         "command": "reg_replace",
         "args": { "replacements": [ "WestCoast_2pm_placement" ] }
     },
 ]
```

**Comment by facelessuser** [comment]
Whatever your problem is, it most likely has nothing to do with chaining `\u003F\u0024`.

1. Did you put your rule in the right place?  Is it in your `reg_replace_rules.sublime-setings` file or `reg_replace.sublime-settings`?

2. I have no idea what text you are running this replacement on, so I have no idea if you've even constructed the find pattern correctly. Please post a snippet example you are running this against.

3. This pattern looks invalid: `"_1-_-{\\u003F\\u0024contacts_data_17\\u003F}-_-}"`.

    You should probably escape the `{` and `}` characters if you want to find the literal representation of them. I imagine this pattern isn't even compiling the way you've written it.

   Maybe you wanted: `"_1-_-\\{\\u003F\\u0024contacts_data_17\\u003F}-_-\\}"`, but since I don't see an example of the text you are trying to target, I can only guess if that is what you want 🤷‍♂️ .

Please provide more info, and try to fix your pattern.

**Comment by displayadrian** [comment]
Turns it it works fine - I had an extra character where it didn't belong in the tracking tag

**Comment by facelessuser** [comment]
Glad you got it working.
