### ISSUE TITLE
RegReplace Command Pallete Search Not Showing Created Command

### ISSUE THREAD

**Issue by gingaaCS** [facelessuser/RegReplace#88]
---

## Description

Hey, I am a new user and when I search for my created command it doesn't come up, here is my code:

Body:

```js
{
  "replacements": {
    "replace_double_periods": {
      "find": "..",
      "replace": "!",
      "greedy": true,
      "case": false
    },
    "remove_periods": {
      "find": ".",
      "replace": "",
      "greedy": true,
      "case": false
    },
   "replace_exclamation": {
      "find": "!",
      "replace": ".",
      "greedy": true,
      "case": false
    }
  }
}
```

Command:

```js
[
  {
    "caption": "RegReplace: Replace !'s",
    "command": "reg_replace",
    "args": {
      "replacements": [
        "replace_double_periods",
        "remove_periods",
        "replace_exclamation"
      ]
    }
  }
]
```

## Support Info

I tried getting the support info, but the text was greyed out instead of black(unclickable).
...

**Comment by gingaaCS** [comment]
I searched "RegReplace:" but all that comes up are the User Rules and Settings

**Comment by facelessuser** [comment]
Post the name of the setting files you put the rules in and the command in. I haven't evaluated the content yet, but I want to make sure you put them in the correct files.

**Comment by gingaaCS** [comment]
Body is under Rules-User and the Command is under Commands-User

**Comment by facelessuser** [comment]
The command worked for me. The big problem I saw was that it replaced everything in my file due to bad patterns. I would change your rules to this:

```js
{
  "replacements": {
    "replace_double_periods": {
      "find": "\\.\\.",
      "replace": "!",
      "greedy": true,
      "case": false
    },
    "remove_periods": {
      "find": "\\.",
      "replace": "",
      "greedy": true,
      "case": false
    },
   "replace_exclamation": {
      "find": "!",
      "replace": ".",
      "greedy": true,
      "case": false
    }
  }
}
```

If you are still having issues, you will have to look in your console and see if there are errors and post them here, but from what I can tell, the command appears and works as expected (save the pattern updates I described above that you need).

**Comment by gingaaCS** [comment]
For some reason it won't let me into the console.

**Comment by facelessuser** [comment]
What won't let you into the console? How are you trying to get into the console? I believe the shortcut for the console is ` ctrl+` `.

Unfortunately, RegReplace has nothing to do with the console not opening, and I can't help unless you give me more info. If you get desperate, you can always try a revert in Sublime: https://www.sublimetext.com/docs/3/revert.html.

**Comment by gingaaCS** [comment]
I dont think I need to look at the console since RegReplace isn't showing up when I look for it, also I am not allowed to open settings for RegReplace.
![regreplace](https://user-images.githubusercontent.com/51132140/58880196-fd0cb780-869c-11e9-8550-80b6e8bf8198.PNG) 
![sublime settings](https://user-images.githubusercontent.com/51132140/58880204-01d16b80-869d-11e9-97ba-729081f7c188.PNG)

**Comment by facelessuser** [comment]
Something is making it difficult for the settings file to open, the errors would be in the console. I can't debug without adequate info. All I can say is things like uninstall RegReplace, then reinstall, and restart Sublime.

From my perspective, everything is working fine as what you've provided me works on my Sublime install. Whatever you are experiencing, it is specific to your environment, maybe even because of something you've accidentally done that isn't being expressed here in this issue.

To be honest, I don't even know basic things like what version of Sublime are you on, did you install with package control or did you install manually (which is not recommended), etc.

**Comment by gingaaCS** [comment]
I used package control and all the console says is this "error: The settings file "res://Packages/RegReplace/reg_replace.sublime-settings" could not be opened"

**Comment by facelessuser** [comment]
What version of Sublime?

**Comment by gingaaCS** [comment]
Just Sublime Text 3

**Comment by facelessuser** [comment]
3 what? What does it say in Sublime's about window?

**Comment by gingaaCS** [comment]
3.2.1

**Comment by facelessuser** [comment]
Something must be corrupted. Try uninstalling and reinstalling RegReplace. Check the console if there were errors during reinstall. Restart Sublime afterwards if everything installed without errors. If that doesn't work, try a Sublime revert.

Without a specific error, that is the best I can suggest.. This is all assuming you are putting good formatted settings in the right file.

**Comment by gingaaCS** [comment]
Okay I should be able to figure it out, thanks.
