### ISSUE TITLE
Regular expression help

### ISSUE THREAD

**Issue by stillhope** [facelessuser/RegReplace#97]
Catalina OS X, ST3
I have been using documentation, facelessuser.GitHub.io/regreplace/
I think I am too non technical many times. I am struggling with what I sense is basic regular expression.
Is there some place in documentation, I have missed?

**firstly**, all for a selection of text,

regular expression to denote numbers located only at end of line

regular expression to denote any number that does not have suffix : or suffix . --- - [0-9] is not working as numbers are used for other means in text

Regular expression to denote numbers located at end of a line

regular expression to denote end of a line ---- //

This information I thought I need so I can can add new entry in regplace, 
to find :
numbers at end of line
Replace with
Deliminator ; and number 

(said another way, insert deliminator before numbers, when the numbers are located at the end of line)

**secondly**,
 to use regreplace to automate insert of numbered bullets in block of plain text using ST3. In a selection of text. Like I was doing in a RTF text editor (rich text format).
For example
Find beginning of line number (number then dot)
1. A big 
2. Bee

replace with (8. then same number, and no dot at end)
8.1 A big
8.2 Bee

**thirdly**
Find (in a selection, text with capitals in middle of word)
 FrequencyResponseFundamentals
 
Replace with: split into words, or (said another add spaces, Sentence Case  )
 Frequency Response Fundamentals

**fourth**:
Find : selection of text I highlight, get format styling eg tabs, bullets etc..
Replace with : copy this formatting to the selected text 
Excel calls it "copy format"

Thankyou for any help.

**Comment by facelessuser** [comment]
Can you post exactly what you tried?

**Comment by stillhope** [comment]
I have tried many things for 3 days now. I try and be succinct. I must be missing something basic.

1. **find end of line numbers and insert deliminator**
before
10.1 Introduction 401
after
10.1 Introduction; 401

Tried:
Regular Expression button pressed

case: 3 digits
find
\s\d\d\d$
replace with
;\s\d\d\d$

case: 2 digits
find
\s\d\d$
replace with
;\s\d\d$

case: 1 digit
find
\s\d$
replace with
;\s\d$

result: failed, replaces the numbers with letters sddd


2. **Change Bullet style**
before
  1. Introduction; 705
  2. Oscillator Principles of Operation; 706
  3. RC Phase-Shift Oscillator; 707
  4. Wien-Bridge Oscillator; 711
  5. Colpitts Oscillator; 715
after
  10.1 Introduction; 705
  10.2 Oscillator Principles of Operation; 706
  10.3 RC Phase-Shift Oscillator; 707
  10.4 Wien-Bridge Oscillator; 711
  10.5 Colpitts Oscillator; 715

Tried:
Regular Expression button pressed
selection (row 188-192) 
find
\d[.]^
replace with
10[.]\d^

result: failed. it says unable to find \d[.]^


3 **Split string into words**
I have been using https://www.appdevtools.com/case-converter
Before
FrequencyResponseFundamentals
After (Capital Case)
Frequency Response Fundamentals
After (Sentence Case)
Frequency response fundamentals

Tried:
find
\U
replace with
space\U

there is an sublime text converter case addon. It deals with case for programming rather than prose.  I could not find option of Capital Case or Sentence Case.

**Comment by facelessuser** [comment]
Yeah, replacing with `;\s\d\d\d$` is not going to work. You would need to use a capturing group `()` and then use the capture reference, in this case, `\1` as it is the first capturing group.

Find: `(\s\d\d\d)$`

Replace: `;\1`

---

So here we are going to demo the first two examples you gave.

```js
{
	"format": "3.0",
	"replacements":
	{
		"demo1":
		{
			// Reduce \d\d\d to \d{3} and wrap content we wish to reuse in replace
			// in a capture group '()'
			"find": "(\\s\\d{3})$",
			"replace": ";\\1"
		}
		"demo2":
		{
			// Find the start of the line `^` and then a number followed by `.`
			// We want to reuse the number in the replace, so capture it.
			"find": "^(\\d)\\.",
			"replace": "10.\\1"
		}
	}
}
```

We create a command in our command file and chain `demo2` right after `demo1`:

```js
[
    {
       "caption": "Reg Replace: Demo",
       "command": "reg_replace",
       "args": {
            "replacements": ["demo1", "demo2"]
        }
    }
]
```

Here is the command in action:

![regreplace_demo](https://user-images.githubusercontent.com/1055125/120093922-9cbd7e80-c0da-11eb-8f0a-658cacf557e0.gif)

---

As for the last example. Sublime's regex uses Boost regex, which does allow you to capture uppercase with `\U`, Python regex does not. We are actually using Python's regex under the hood. You can enable a special library that RegReplace can use called `backrefs` which allows you to use some Unicode properties if you like which can essentially capture the same thing.

Now, the documentation sadly isn't quite up to date as it states that we support `\U` as `\C` (because Python already uses `\U` to denote Unicode references), but that is no longer correct. Support for `\C` was dropped, and you have to use the Unicode property `\p{uppercase}`.

So, assuming you have enabled `extended_back_references` via the global option in your `reg_replace.sublime-settings` file, this should work.

Rules:

```js
{
	"format": "3.0",
	"replacements":
	{
		"demo3":
		{
			"find": "(\\p{uppercase})",
			"replace": " \\1"
		},
	}
}
```

Command:

```js
[
    {
       "caption": "Reg Replace: Demo Case",
       "command": "reg_replace",
       "args": {
            "replacements": ["demo3"]
        }
    }
]
```

Results:

![regreplace_demo_case](https://user-images.githubusercontent.com/1055125/120094315-e14a1980-c0dc-11eb-8aae-cf0726d83560.gif)

---

I don't normally go through such lengths to solve regex issues for people, I'm normally more concerned with just explain how RegReplace works and addressing issues, but hopefully this helps.

As discussed, I need to update the documents in regards to `backrefs` as it is out of date, so I will take that as an action item.

**Comment by stillhope** [comment]
Oh this perfect!
 Thankyou ever so much for going to extra effort. I knew I missing some fundamental logic. Capture Groups.
